version: "3.8"

services: 
  api:
    container_name: api
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "user=sidejob-db password=sidejob-db host=db port=5432 dbname=sidejob-db sslmode=disable"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sidejob-db
      - POSTGRES_PASSWORD=sidejob-db
      - POSTGRES_DB=sidejob-db
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sidejob-db -d sidejob-db"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  data:

